# Generated by Django 2.2 on 2020-02-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecomments',
            old_name='coerse',
            new_name='course',
        ),
    ]
