# Generated by Django 2.2 on 2020-02-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200209_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_years',
            field=models.IntegerField(default=0, verbose_name='工作年限'),
        ),
    ]
